name: sudoku
description: Sudoku game.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  desktop: any
  shared_preferences: ^2.0.18
  wakelock: ^0.6.2

#dependency_overrides:
#  desktop:
#    path:
#      ../desktop/desktop

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets: 
    - assets/sudoku.png