name: sudoku
description: Sudoku game.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  desktop: ^4.0.0
  shared_preferences: ^2.1.1
  wakelock: ^0.6.2
  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets: 
    - assets/sudoku.png